############################################################
# +------------------------------------------------------+ #
# |                       Config                         | #
# +------------------------------------------------------+ #
############################################################

# Rares have a chance to spawn on any natural mob spawns.
# If spawn-chance is 1000, rares have a 0.1% chance to spawn any time a mob spawns.
spawn-chance: 25000
# I found that 25000 works well for my own server.
# (0.004%)

# Different spawn groups of rares, unaffected by eachother's chances and weights.
# Any rare entity without a group will default to group "default", using settings from the file.
# Any unset settings will use default settings.
spawn-groups:
 group1: # Full example
  id: group1
  chance: 10000
  log-spawns: false # Show spawns in console, this example spawns faster, so we won't show spawns in the console for them.
  spawn-above-ground: true
  spawn-range-max: 50
  spawn-limit:
   amount: 9
   range: 50
  firework: false
  blacklist:
   - WorldName
   - WorldName_nether
   - WorldName_the_end
  shared-drops:
  #- item:amount:chance
  #- material:amount
  #- material:amount:chance
  #- material:min-max:chance
   - template:1
   - DIAMOND:1:20
   - EMERALD:1-4:20
 group2: # All except "id" are optional
  id: group2
  shared-drops: [] # Drops can be empty to not include any shared at all.

# Should rares be forced above ground?
# Otherwise they can spawn in caves.
spawn-above-ground: true

# Maximum distance away from players rares can spawn.
# The upper limit of this setting depends on server settings.
# -1 for unlimited range.
spawn-range-max: 100

# How many rares can spawn in the around each player?
spawn-limit:
 amount: 5 # -1 to disable
 range: 100

# Should we spawn firework where the rare has spawned?
spawn-firework:
 enabled: true
 amount: 5
 delay: 20

# List of worlds where rares won't spawn.
blacklist:
 - WorldName
 - WorldName_nether
 - WorldName_the_end

# Immunity Frames; How often in ticks the rares can be hit, default 20 ticks.
iframes: 20 # This is overridden if the rare has this setting itself.

# How many times RareSpawns should attempt to fix a rare's max health.
# Due to bugs with wolves for example, they quite often get their max health reset to 8, regardless of what is set.
# You can disable this by setting it to -1, but could become an infinite clash if another plugin or datapack is interfering.
health-fix-cap: 7

# Should we remove old removed rares from the world?
remove-old-rares: false

# Items that all rares have a chance to drop
shared-drops:
#- item:amount:chance
#- material:amount
#- material:amount:chance
#- material:min-max:chance
 - template:1
 - DIAMOND:1:20
 - EMERALD:1-4:20
 